# Generated by Django 5.2 on 2025-05-07 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable, se genera automáticamente (máx. 50 palabras)', null=True, unique=True)),
                ('resumen', models.TextField(blank=True, help_text='Un resumen breve que se muestra en tarjetas')),
                ('tecnologias', models.TextField(help_text='Ej: Django, PostgreSQL, Bootstrap')),
                ('caracteristicas', models.TextField(blank=True, help_text='Características incluidas en el proyecto')),
                ('arquitectura', models.TextField(blank=True, help_text='Arquitectura usada para la construcción')),
                ('imagen_miniatura', models.FileField(blank=True, help_text='Solo se permiten archivos .SVG', null=True, upload_to='proyectos/miniaturas/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('retos', models.TextField(blank=True)),
                ('proximos_pasos', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo de la persona', max_length=200)),
                ('ocupacion', models.CharField(blank=True, max_length=200, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('hoja_de_vida', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=200)),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('mensaje_bienvenida', models.CharField(max_length=200)),
                ('resumen_profesional', models.TextField()),
                ('mision', models.TextField(blank=True, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='portafolio/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portafolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='portafolio.persona')),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stacks',
            },
        ),
    ]
