# Generated by Django 5.2 on 2025-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL amigable, se genera automáticamente', null=True, unique=True)),
                ('descripcion', models.TextField()),
                ('resumen', models.TextField(blank=True, help_text='Un resumen breve que se muestra en tarjetas')),
                ('tecnologias', models.TextField(help_text='Ej: Django, PostgreSQL, Bootstrap')),
                ('caracteristicas', models.TextField(blank=True, help_text='Características incluidas en el proyecto')),
                ('arquitectura', models.TextField(blank=True, help_text='Arquitectura usada para la construcción')),
                ('imagen_miniatura', models.FileField(blank=True, help_text='Solo se permiten archivos .SVG', null=True, upload_to='proyectos/miniaturas/')),
                ('github_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('retos', models.TextField(blank=True)),
                ('proximos_pasos', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
